<a href="https://colab.research.google.com/github/Bgail-ranu/Data-science/blob/main/Week2_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import calendar

In [3]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Warehouse_and_Retail_Sales.csv')
df.head()

Mounted at /content/drive

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0
2,2020,1,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0
3,2020,1,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0
4,2020,1,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0

In [4]:
df.shape

(307645, 9)

In [5]:
df.isnull().sum()

YEAR                  0
MONTH                 0
SUPPLIER            167
ITEM CODE             0
ITEM DESCRIPTION      0
ITEM TYPE             1
RETAIL SALES          3
RETAIL TRANSFERS      0
WAREHOUSE SALES       0
dtype: int64

In [6]:
df_c = df.drop(columns=['ITEM DESCRIPTION', 'ITEM CODE'])
#df_c['SUPPLIER'].fillna('Unknown', inplace=True)
df_c.fillna({'SUPPLIER': 'Unknown'}, inplace=True)
df_c = df_c.dropna(subset=['ITEM TYPE'])
df_c = df_c.dropna(subset=['RETAIL SALES'])
df.shape, df_c.shape, df_c.isnull().sum()

((307645, 9),
 (307641, 7),
 YEAR                0
 MONTH               0
 SUPPLIER            0
 ITEM TYPE           0
 RETAIL SALES        0
 RETAIL TRANSFERS    0
 WAREHOUSE SALES     0
 dtype: int64)

In [7]:
df_c.duplicated().sum()

np.int64(109014)

In [8]:
df_c = df_c.drop_duplicates()
df_c.shape

(198627, 7)

In [9]:
df['YEAR'].value_counts().sort_index()

YEAR
2017     96284
2018     26445
2019    138638
2020     46278
Name: count, dtype: int64

In [10]:
df.YEAR

0         2020
1         2020
2         2020
3         2020
4         2020
          ...
307640    2020
307641    2020
307642    2020
307643    2020
307644    2020
Name: YEAR, Length: 307645, dtype: int64

In [31]:
month_map = {
    1: "January", 2: "February", 3: "March",
    4: "April", 5: "May", 6: "June",
    7: "July", 8: "August", 9: "September",
    10: "October", 11: "November", 12: "December"
}

df_c['MONTH'] = df['MONTH'].map(month_map)

print(df_c[['MONTH']].tail())

            MONTH
307639  September
307641  September
307642  September
307643  September
307644  September

In [33]:
df_c.loc[182109:, 'MONTH'].head(10)

182109    February
182110    February
182111    February
182112       March
182113       March
182114       March
182115       March
182116       March
182117       March
182118       March
Name: MONTH, dtype: object

In [13]:
df_c.columns

Index(['YEAR', 'MONTH', 'SUPPLIER', 'ITEM TYPE', 'RETAIL SALES',
       'RETAIL TRANSFERS', 'WAREHOUSE SALES'],
      dtype='object')

In [12]:
df_c['ITEM TYPE'].value_counts().sort_index()

ITEM TYPE
BEER             29546
DUNNAGE             95
KEGS              4848
LIQUOR           56184
NON-ALCOHOL       1833
REF                127
STR_SUPPLIES       394
WINE            105600
Name: count, dtype: int64

In [36]:
item_analysis = df_c.groupby('ITEM TYPE')['RETAIL SALES'].agg([
    ('total_sales', 'sum'),
    ('Average_Sales', 'mean'),
    ('Minimum_Sales', 'min'),
    ('Maximum_Sales', 'max'),
    ('num_sales', 'count')
])
item_analysis = item_analysis.sort_values('total_sales', ascending=False)
print(item_analysis)

              total_sales  Average_Sales  Minimum_Sales  Maximum_Sales  \
ITEM TYPE
LIQUOR          799181.92      14.224369          -2.47        1816.49
WINE            743544.84       7.041144          -6.49         813.84
BEER            574056.45      19.429244          -0.13        1494.00
NON-ALCOHOL      34084.31      18.594823          -0.08        2739.00
STR_SUPPLIES      2737.48       6.947919           0.00         368.64
REF                663.63       5.225433          -0.08          36.00
KEGS                 0.00       0.000000           0.00           0.00
DUNNAGE              0.00       0.000000           0.00           0.00

              num_sales
ITEM TYPE
LIQUOR            56184
WINE             105600
BEER              29546
NON-ALCOHOL        1833
STR_SUPPLIES        394
REF                 127
KEGS               4848
DUNNAGE              95

In [37]:
df_c.to_csv('Warehouse_cleaned.csv', index=False)

In [38]:
gdrive_path = '/content/drive/MyDrive/Warehouse_cleaned.csv'

df_c.to_csv(gdrive_path, index=False)

print(f"A new permanent file has been saved to: {gdrive_path}")

A new permanent file has been saved to: /content/drive/MyDrive/Warehouse_cleaned.csv