<a href="https://colab.research.google.com/github/Bgail-ranu/Data-science/blob/main/Week5_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LOAD & INSPECT**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Warehouse_cleaned.csv')
df.head()

Mounted at /content/drive

,YEAR,MONTH,SUPPLIER,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,MONTHE
0,2020,January,REPUBLIC NATIONAL DISTRIBUTING CO,WINE,0.00,0.0,2.0,NaN
1,2020,January,PWSWN INC,WINE,0.00,1.0,4.0,NaN
2,2020,January,RELIABLE CHURCHILL LLLP,BEER,0.00,0.0,1.0,NaN
3,2020,January,LANTERNA DISTRIBUTORS INC,WINE,0.00,0.0,1.0,NaN
4,2020,January,DIONYSOS IMPORTS INC,WINE,0.82,0.0,0.0,NaN

In [4]:
df = df.drop(columns=['MONTHE'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198627 entries, 0 to 198626
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              198627 non-null  int64
 1   MONTH             198627 non-null  object
 2   SUPPLIER          198627 non-null  object
 3   ITEM TYPE         198627 non-null  object
 4   RETAIL SALES      198627 non-null  float64
 5   RETAIL TRANSFERS  198627 non-null  float64
 6   WAREHOUSE SALES   198627 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 10.6+ MB

In [8]:
df.shape

(198627, 7)

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,198627.0,2018.416645,1.086714,2017.00,2017.00,2019.00,2019.00,2020.00
RETAIL SALES,198627.0,10.845800,38.024650,-6.49,0.25,1.63,7.75,2739.00
RETAIL TRANSFERS,198627.0,10.731799,37.086737,-38.49,0.00,1.00,8.00,1990.83
WAREHOUSE SALES,198627.0,38.030455,310.272485,-7800.00,0.00,2.00,10.00,18317.00

# **Identify Features and Target Variable**

In [9]:
df.columns

Index(['YEAR', 'MONTH', 'SUPPLIER', 'ITEM TYPE', 'RETAIL SALES',
       'RETAIL TRANSFERS', 'WAREHOUSE SALES'],
      dtype='object')

In [10]:
y = df['WAREHOUSE SALES']
x = df.drop(columns=['WAREHOUSE SALES'])

In [11]:
x.head()

,YEAR,MONTH,SUPPLIER,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS
0,2020,January,REPUBLIC NATIONAL DISTRIBUTING CO,WINE,0.00,0.0
1,2020,January,PWSWN INC,WINE,0.00,1.0
2,2020,January,RELIABLE CHURCHILL LLLP,BEER,0.00,0.0
3,2020,January,LANTERNA DISTRIBUTORS INC,WINE,0.00,0.0
4,2020,January,DIONYSOS IMPORTS INC,WINE,0.82,0.0

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198627 entries, 0 to 198626
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              198627 non-null  int64
 1   MONTH             198627 non-null  object
 2   SUPPLIER          198627 non-null  object
 3   ITEM TYPE         198627 non-null  object
 4   RETAIL SALES      198627 non-null  float64
 5   RETAIL TRANSFERS  198627 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 9.1+ MB

# **Cat/Num features**

In [13]:
cat_features = x.select_dtypes(include=['object']).columns
num_features = x.select_dtypes(include=['int64', 'float64']).columns
cat_features, num_features

(Index(['MONTH', 'SUPPLIER', 'ITEM TYPE'], dtype='object'),
 Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS'], dtype='object'))

# **Preprocessing & Encoding**

In [14]:
scaler = StandardScaler()
encoder = OneHotEncoder(handle_unknown='ignore')
preprocessor = ColumnTransformer(
    transformers = [
        ('num', scaler, num_features),
        ('cat', encoder, cat_features)
    ]
)

# **Train-Test Split**

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((158901, 6), (39726, 6), (158901,), (39726,))

# **Build the Regression Model**

In [16]:
lr = LinearRegression()
model = Pipeline(
    steps = [
        ('preprocessor', preprocessor),
        ('regressor', lr)
    ]
)
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['MONTH', 'SUPPLIER', 'ITEM TYPE'], dtype='object'))])),
                ('regressor', LinearRegression())])

# **Train the Model**

In [17]:
model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS'], dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['MONTH', 'SUPPLIER', 'ITEM TYPE'], dtype='object'))])),
                ('regressor', LinearRegression())])

# **Make Predictions**

In [18]:
y_pred = model.predict(x_test)

# **Model Evaluation**

In [20]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_absolute_error(y_test, y_pred))
mae, rmse

(63.20570548276683, np.float64(7.950201600133599))

In [21]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.4246349752153771

# **Feature Names**

In [25]:
feature_name = model.named_steps['preprocessor'].get_feature_names_out()
coefficient = model.named_steps['regressor'].coef_
coef_df = pd.DataFrame({
    'Feature': feature_name,
    'Coefficient': coefficient
}).sort_values(by ='Coefficient', ascending = False)
coef_df.head(20)

                                   Feature  Coefficient
95             cat__SUPPLIER_CROWN IMPORTS   958.862913
121                  cat__SUPPLIER_Default   630.522466
167                 cat__SUPPLIER_HAMCO DC   562.270378
374                  cat__SUPPLIER_Unknown   506.461319
190   cat__SUPPLIER_KAHN PAPER COMPANY INC   463.608369
171             cat__SUPPLIER_HEINEKEN USA   458.658590
408                    cat__ITEM TYPE_BEER   376.083403
415                    cat__ITEM TYPE_WINE   327.925111
227   cat__SUPPLIER_MILLER BREWING COMPANY   310.433651
411                  cat__ITEM TYPE_LIQUOR   306.891592
410                    cat__ITEM TYPE_KEGS   285.876387
412             cat__ITEM TYPE_NON-ALCOHOL   263.889592
30        cat__SUPPLIER_ANHEUSER BUSCH INC   163.853808
2                    num__RETAIL TRANSFERS    89.182837
256         cat__SUPPLIER_PABST BREWING CO    83.912319
405        cat__SUPPLIER_YUENGLING BREWERY    71.344380
81             cat__SUPPLIER_CHEF SOUS LLC    70.189209
407               cat__SUPPLIER_ZURENA LLC    67.309440
51            cat__SUPPLIER_BITTERMILK LLC    59.623074
162  cat__SUPPLIER_GRAIL POINT BREWERY LLC    50.548725